In [21]:
input_text = '''
[0,6]=(g1.d0)
[0,11]=(g1.d9)
[3,0]=(g0.d1)
[4,3]=(g0.d9)
[5,4]=(g0.d3)
[5,11]=(g1.d0)
[6,0]=(g0.d0)
[6,5]=(g0.d9)
[9,6]=(g0.d1)
[10,9]=(g0.d9)
[11,5]=(g0.d0)
[11,10]=(g0.d3)
'''
    
def parse_file(file_content):
    rows = file_content.strip().split("\n")
    data = {}
    for row in rows:
        coord, value = row.split("=")
        r, c = [int(x) for x in coord.strip("[]").split(",")]
        if r not in data:
            data[r] = {}
        data[r][c] = value
        
    return data

result = parse_file(input_text)

In [22]:
import pandas as pd

def print_table(data):
    max_row = max(data.keys())
    max_col = max(max(d.keys()) for d in data.values())
    
    df = pd.DataFrame(index=range(max_row + 1), columns=range(max_col + 1))
    
    for r, row_data in data.items():
        for c, value in row_data.items():
            df.at[r, c] = value
            
    return df.fillna('ε')

In [23]:
print_table(result)

,0,1,2,3,4,5,6,7,8,9,10,11
0,ε,ε,ε,ε,ε,ε,(g1.d0),ε,ε,ε,ε,(g1.d9)
1,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε
2,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε
3,(g0.d1),ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε
4,ε,ε,ε,(g0.d4),(g0.d9),ε,ε,ε,ε,ε,ε,ε
5,ε,ε,ε,ε,(g0.d3),ε,ε,ε,ε,ε,ε,(g1.d0)
6,(g0.d0),ε,ε,ε,ε,(g0.d9),ε,ε,ε,ε,ε,ε
7,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε
8,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε,ε
9,ε,ε,ε,ε,ε,ε,(g0.d1),ε,ε,ε,ε,ε
10,ε,ε,ε,ε,ε,ε,ε,ε,ε,(g0.d4),(g0.d9),ε
11,ε,ε,ε,ε,ε,(g0.d0),ε,ε,ε,ε,(g0.d3),ε

[None, '(g0.d2)', None, None, None, None, '(g1.d0)', None, None, None, None, '(g1.d9)']
['(g0.d1)']
[None, '(g0.d10)', None, '(g0.d5)']
['(g0.d3)']
[None, None, None, '(g0.d20)', None, '(g0.d7)']
[None, None, '(g0.d6)', None, '(g0.d8)', None, None, None, None, None, None, '(g1.d0)']
['(g0.d0)', None, None, None, None, '(g0.d9)', None, '(g0.d2)']
[None, None, None, None, None, None, '(g0.d1)']
[None, None, None, None, None, None, None, '(g0.d10)', None, '(g0.d5)']
[None, None, None, None, None, None, '(g0.d3)']
[None, None, None, None, None, None, None, None, None, '(g0.d20)', None, '(g0.d7)']
[None, None, None, None, None, '(g0.d0)', None, None, '(g0.d6)', None, '(g0.d8)']